# Generated by Django 5.2.8 on 2025-11-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=40)),
                ('course_code', models.CharField(max_length=40)),
                ('course_name', models.CharField(max_length=3)),
                ('department', models.CharField(max_length=40)),
                ('units', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Education_Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=40)),
                ('school_name', models.CharField(max_length=40)),
                ('school_address', models.CharField(max_length=155)),
                ('course', models.CharField(choices=[('BSSW', 'BSSW'), ('BSAIS', 'BSAIS'), ('BSIT', 'BSIT'), ('BSPA', 'BSPA'), ('BTVTE', 'BTVTE')], default='BSIT')),
                ('year', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Family_Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=40)),
                ('mother_name', models.CharField(max_length=40)),
                ('number_of_siblings', models.CharField(max_length=3)),
                ('guardian_name', models.CharField(max_length=40)),
                ('guardian_contact', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('Rather not say', 'Rather not say'), ('Female', 'Female'), ('Male', 'Male')], default='Male')),
                ('address', models.CharField(max_length=155)),
                ('gmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=40)),
                ('course_id', models.CharField(max_length=40)),
                ('semester', models.CharField(max_length=3)),
                ('amount', models.CharField(max_length=40)),
                ('Due_date', models.DateField()),
            ],
        ),
    ]
