# Generated by Django 5.2.8 on 2025-11-21 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_background',
            name='course',
            field=models.CharField(choices=[('BSPA', 'BSPA'), ('BTVTE', 'BTVTE'), ('BSIT', 'BSIT'), ('BSSW', 'BSSW'), ('BSAIS', 'BSAIS')], default='BSIT'),
        ),
        migrations.AlterField(
            model_name='personal_background',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Rather not say', 'Rather not say'), ('Male', 'Male')], default='Male'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
