# Generated by Django 5.2.8 on 2025-11-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0002_alter_education_background_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_background',
            old_name='gmail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='education_background',
            name='course',
            field=models.CharField(choices=[('BSIT', 'BSIT'), ('BSAIS', 'BSAIS'), ('BSPA', 'BSPA'), ('BTVTE', 'BTVTE'), ('BSSW', 'BSSW')], default='BSIT'),
        ),
        migrations.AlterField(
            model_name='personal_background',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Rather not say', 'Rather not say'), ('Female', 'Female')], default='Male'),
        ),
    ]
