# Generated by Django 5.2.8 on 2025-11-21 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0003_rename_gmail_personal_background_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='education_level',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='student_list.personal_background'),
        ),
        migrations.AddField(
            model_name='education_background',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='student_list.personal_background'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='education_level',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='family_background',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='student_list.personal_background'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='education_level',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tuition',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuition', to='student_list.personal_background'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='education_background',
            name='course',
            field=models.CharField(choices=[('BSPA', 'BSPA'), ('BSAIS', 'BSAIS'), ('BSSW', 'BSSW'), ('BTVTE', 'BTVTE'), ('BSIT', 'BSIT')], default='BSIT', null=True),
        ),
        migrations.AlterField(
            model_name='education_background',
            name='education_level',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='education_background',
            name='school_address',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='education_background',
            name='school_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='education_background',
            name='year',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='family_background',
            name='father_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='family_background',
            name='guardian_contact',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='family_background',
            name='guardian_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='family_background',
            name='mother_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='family_background',
            name='number_of_siblings',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='personal_background',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Rather not say', 'Rather not say')], default='Male'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='amount',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='course_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='payment_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='semester',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
