# Generated by Django 5.2.8 on 2025-11-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0004_course_education_level_course_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family_background',
            name='education_level',
        ),
        migrations.AlterField(
            model_name='education_background',
            name='course',
            field=models.CharField(choices=[('BSSW', 'BSSW'), ('BSAIS', 'BSAIS'), ('BSPA', 'BSPA'), ('BTVTE', 'BTVTE'), ('BSIT', 'BSIT')], default='BSIT', null=True),
        ),
        migrations.AlterField(
            model_name='personal_background',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Rather not say', 'Rather not say'), ('Female', 'Female')], default='Male'),
        ),
    ]
