# Generated by Django 5.2.8 on 2025-11-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0005_remove_family_background_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='education_level',
        ),
        migrations.AlterField(
            model_name='education_background',
            name='course',
            field=models.CharField(choices=[('BSIT', 'BSIT'), ('BSAIS', 'BSAIS'), ('BTVTE', 'BTVTE'), ('BSPA', 'BSPA'), ('BSSW', 'BSSW')], default='BSIT', null=True),
        ),
        migrations.AlterField(
            model_name='personal_background',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not say', 'Rather not say')], default='Male'),
        ),
    ]
