# Generated by Django 5.2.8 on 2025-11-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0006_remove_course_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_background',
            name='course',
            field=models.CharField(choices=[('BSSW', 'BSSW'), ('BSPA', 'BSPA'), ('BTVTE', 'BTVTE'), ('BSIT', 'BSIT'), ('BSAIS', 'BSAIS')], default='BSIT', null=True),
        ),
        migrations.AlterField(
            model_name='personal_background',
            name='gender',
            field=models.CharField(choices=[('Rather not say', 'Rather not say'), ('Male', 'Male'), ('Female', 'Female')], default='Male'),
        ),
    ]
